map_frame: map
base_frame: base_link_2
odom_frame: odom_2
map_update_interval: 0.1
maxRange: 5.0
maxUrange: 5.0
sigma: 0.05
kernelSize: 1
lstep: 0.1
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 1
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
linearUpdate: 0.1
angularUpdate: 0.05
temporalUpdate: -1 
resampleThreshold: 0.5
particles: 100
xmin: -10.0
ymin: -10.0
xmax: 10.0
ymax: 10.0
delta: 0.05
llsamplerange: 0.1
llsamplestep: 0.1
lasamplerange: 0.05
lasamplestep: 0.05


