set(_CATKIN_CURRENT_PACKAGE "auto_jetracer")
set(auto_jetracer_VERSION "0.0.0")
set(auto_jetracer_MAINTAINER "jetson <jetson@todo.todo>")
set(auto_jetracer_PACKAGE_FORMAT "2")
set(auto_jetracer_BUILD_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "urdf" "apriltag_ros" "libpcl-all-dev" "pcl_ros")
set(auto_jetracer_BUILD_EXPORT_DEPENDS "roscpp" "apriltag_ros" "pcl_ros" "rospy" "sensor_msgs" "std_msgs" "urdf")
set(auto_jetracer_BUILDTOOL_DEPENDS "catkin")
set(auto_jetracer_BUILDTOOL_EXPORT_DEPENDS )
set(auto_jetracer_EXEC_DEPENDS "libpcl-all" "roscpp" "rospy" "sensor_msgs" "std_msgs" "urdf")
set(auto_jetracer_RUN_DEPENDS "libpcl-all" "roscpp" "rospy" "sensor_msgs" "std_msgs" "urdf" "apriltag_ros" "pcl_ros")
set(auto_jetracer_TEST_DEPENDS )
set(auto_jetracer_DOC_DEPENDS )
set(auto_jetracer_URL_WEBSITE "")
set(auto_jetracer_URL_BUGTRACKER "")
set(auto_jetracer_URL_REPOSITORY "")
set(auto_jetracer_DEPRECATED "")