// Generated by gencpp from file custom_msgs_optitrack/custom_opti_pose_stamped_msg.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_OPTITRACK_MESSAGE_CUSTOM_OPTI_POSE_STAMPED_MSG_H
#define CUSTOM_MSGS_OPTITRACK_MESSAGE_CUSTOM_OPTI_POSE_STAMPED_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_msgs_optitrack
{
template <class ContainerAllocator>
struct custom_opti_pose_stamped_msg_
{
  typedef custom_opti_pose_stamped_msg_<ContainerAllocator> Type;

  custom_opti_pose_stamped_msg_()
    : header()
    , x(0.0)
    , y(0.0)
    , rotation(0.0)  {
    }
  custom_opti_pose_stamped_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , rotation(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _rotation_type;
  _rotation_type rotation;





  typedef boost::shared_ptr< ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator> const> ConstPtr;

}; // struct custom_opti_pose_stamped_msg_

typedef ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<std::allocator<void> > custom_opti_pose_stamped_msg;

typedef boost::shared_ptr< ::custom_msgs_optitrack::custom_opti_pose_stamped_msg > custom_opti_pose_stamped_msgPtr;
typedef boost::shared_ptr< ::custom_msgs_optitrack::custom_opti_pose_stamped_msg const> custom_opti_pose_stamped_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator1> & lhs, const ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.rotation == rhs.rotation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator1> & lhs, const ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs_optitrack

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70bfefdfc7d1f29f125789ac694c643e";
  }

  static const char* value(const ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70bfefdfc7d1f29fULL;
  static const uint64_t static_value2 = 0x125789ac694c643eULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs_optitrack/custom_opti_pose_stamped_msg";
  }

  static const char* value(const ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32 x\n"
"float32 y\n"
"float32 rotation\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.rotation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct custom_opti_pose_stamped_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs_optitrack::custom_opti_pose_stamped_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "rotation: ";
    Printer<float>::stream(s, indent + "  ", v.rotation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_OPTITRACK_MESSAGE_CUSTOM_OPTI_POSE_STAMPED_MSG_H
